build:
  docker:
    worker: Dockerfile
      build: .
      environment:
        API_ID: $API_ID
        API_HASH: $API_HASH
        BOT_TOKEN: $BOT_TOKEN
        BOT_USERNAME: $BOT_USERNAME
        DB_CHANNEL: $DB_CHANNEL
        BOT_OWNER: $BOT_OWNER
        DATABASE_URL: $DATABASE_URL
        UPDATES_CHANNEL: $UPDATES_CHANNEL
        LOG_CHANNEL: $LOG_CHANNEL
        BROADCAST_AS_COPY: $BROADCAST_AS_COPY
        FORWARD_AS_COPY: $FORWARD_AS_COPY
